version: '3.8'
services:
  db:
    image: mongo
    volumes:
      - type: volume
        source: mydb
        target: /data/db
  server:
    environment:
      - MONGO_PWD
      - MONGO_USERNAME
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    depends_on:
      - db
    restart: always

volumes:
  mydb:
    external: true
  